### ISSUE TITLE
Implement the block quote feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-block-quote#1]
In https://github.com/ckeditor/ckeditor5/issues/393 we discussed the need to have two separate quote features – message quote and external quotes. 

~~First, we'll work on the message quote as the easier and more general one.~~

EDIT: Upon further discussions, we identified 3 different types of quotes – block, message and pulled quotes. We also understood that the simplest of them, on which we can work right now is the good old block quote. Read more in https://github.com/ckeditor/ckeditor5/issues/393#issuecomment-287853563.

**Comment by Reinmar** [comment]
I've been thinking how to implement this feature in the simplest possible way. The first issue was how to get the list of selected elements to wrap with a quote. I want to base that on the "block" type of elements (defined by the schema – read more here: https://github.com/ckeditor/ckeditor5-engine/issues/532#issuecomment-280916457). Only those blocks will be wrappable and the `<messageQuote>` element must be their immediate parent. This will simplify the implementation a lot.

**Comment by Reinmar** [comment]
Another assumption – in the first version subsequent quotes won't be merged when creating them or deleting content between two existing ones. In fact, perhaps this should be the target behaviour of the message quote feature.

**Comment by scofalik** [comment]
I think this should be final behaviour. I can easily imagine situation when you want to quote multiple parts of message and respond to them all at once. You don't want them to be merged. The only situation when I'd consider merging quotes is when executing delete command. If caret was at the end/beginning of quote and user pressed delete/backspace key. Then we could merge.

**Comment by Reinmar** [comment]
Small change of plans – we realised that we are implementing the good old block quote feature now.  Read more in https://github.com/ckeditor/ckeditor5/issues/393#issuecomment-287853563.

I'll rename this package and all files accordingly.

**Comment by Reinmar** [comment]
Besides renaming, it seems that this is the only problem right now: https://github.com/ckeditor/ckeditor5-engine/issues/710

So, I'll create a PR in this repo very soon.
