### ISSUE TITLE
How to handle lists?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-block-quote#2]
This is what I got now:

![feb-19-2017 16-20-44](https://cloud.githubusercontent.com/assets/156149/23103689/6bfa22f6-f6bf-11e6-86cf-7e5f598b088b.gif)

It's different than CKE4's behaviour where entire list is wrapped. I also compared this with Medium and GitHub's editor (both behave like CKE5's implementation) and TinyMCE (which does an odd thing by putting `<blockquote>` inside list items).

If we'd like to change the behaviour to match CKE4's, then we'll need to figure out how the list feature should notify the quote feature that these items are meant to be treated together.

**Comment by scofalik** [comment]
The presented solution seems the most natural. You quoted exactly what you selected. The same happens when you change/turn off list or convert list to headers, etc.

OTOH, given how (nested) lists are implemented, it would be probably easier to put whole list in quote: https://github.com/ckeditor/ckeditor5-list/issues/13#issuecomment-281034771

**Comment by fredck** [comment]
The behavior on the screencast looks fine.

This seems to be a weird use case for manual quote, so sincerely I don't think we need to spend too much time on this. I would go the easiest way for now and eventually change it in the future if feedback will push us to that.

**Comment by Reinmar** [comment]
OK, thanks. So I'll simply do nothing more :) (the current behaviour is just a result of the simplest possible implementation)

**Comment by scofalik** [comment]
But what about the problem I just mentioned? I don't see clear answer how to handle it right now.

**Comment by Reinmar** [comment]
I replied here: https://github.com/ckeditor/ckeditor5-list/issues/13#issuecomment-281058524. I think we should be fine.

**Comment by Reinmar** [comment]
OK, so in #5 the BQ behaves as we agreed here. Closing.
