### ISSUE TITLE
Feature request: Blockquote with attribution

### ISSUE THREAD

**Issue by rudolfbyker** [ckeditor/ckeditor5-block-quote#37]
Currently I can do this with CKEditor:

```html
<blockquote>
  <p>I have three oranges.</p>
</blockquote>
```

I would like to do this:

```html
<blockquote>
  <p>I have three oranges.</p>
  <cite>Dolf</cite>
</blockquote>
```

At some point, `<cite>` was only to be used for titles, not names, but it seems that the latest draft from W3C allows for names, too. See:

- https://stackoverflow.com/a/49212532/836995
- http://w3c.github.io/html/textlevel-semantics.html#the-cite-element

**Comment by Mgsy** [comment]
Hello, you should create a plugin which will introduce `<cite>` tag. Register a new element in Schema and make a proper model <-> view conversion. Please, take a look at our documentation:
- [Creating a simple plugin guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/creating-simple-plugin.html)
- [Schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/schema.html)
- [Conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html)

**Comment by rudolfbyker** [comment]
Thanks, I'll try that today.
